### ISSUE TITLE
Support Weeks

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#114] opened 2017-05-14 04:58 UTC
We currently support d,m,y for time adjustments.  We should probably also support w - weeks.

**Comment by marc-outins** [comment] 2017-07-24 20:37
@aguynamedryan - In the synpuf_250 data there is a person (person_id = 2) who has a ICD9-CM event of 599.71 (Gross Hematuria) at 2008-10-20 and another icd9-cm event 355.8 (Mononeuritis) at 2008-10-04.  I created a study with with Gross Hematuria as the index event and Mononeuritis as a baseline event.  When I don't set anything for maximum lookback the export returns both events.  Setting maximum lookback to 48w returns only the index event.  Since there is only 17 days or 2.4 weeks between these events I expect a maximum lookback of 48w to find the baseline event.  I also ran the study with 336d for maximum lookback (48w x 7days/w = 336d) and it returned both events.

**Comment by aguynamedryan** [comment] 2017-07-25 21:33
@marc-outins, I did some updates and it looks like this might now be working.

**Comment by marc-outins** [comment] 2017-07-25 21:51
@aguynamedryan  still not working for me.

**Comment by aguynamedryan** [comment] 2017-07-27 00:29
Turns out that Sequel doesn't support weeks as an interval and silently does nothing when given that parameter.

I can either modify ConceptQL to multiply weeks by 7 and adjust the date by that many days, or we can abandon this feature.  Any thoughts?

**Comment by jenniferduryea** [comment] 2017-07-27 20:00
I'm open to either abandoning the feature or multiply weeks by 7 and adjust the days.  This is not a high priority - i.e. Amgen doesn't need this.

**Comment by markdanese** [comment] 2017-07-27 20:11
I think we should add this feature.  We can push back to Broom though.  It isn't hard for users to do this on their own.

**Comment by jenniferduryea** [comment] 2017-07-31 18:53
Confirmed that this works by adding 7d = 1w.  Tested this using the max lookback on a baseline algorithm.  Reported correctly.

**Comment by jenniferduryea** [comment] 2017-08-01 23:00
also confirmed weeks "w" works within algorithms in the Diagram Editor.  Closing this out.

**Closed by jenniferduryea** 2017-08-01 23:00 UTC
Labels: bug, confirm to close
