### ISSUE TITLE
Have operators show their color in the JAM based on the domain set in the CSV file

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#138] opened 2017-07-27 17:20 UTC
Currently, operators created from the generic operator (explained here outcomesinsights/conceptql#106 ) do not have a color assigned to them.  They should be reading from the CSV file, which includes a domain column (described here outcomesinsights/jigsaw#121) .  If a vocabulary is assigned a domain, use the following color scheme to assign that color to the operator in the JAM:
 * visit_occurrence = yellow
 * condition_occurrence = red
 * procedure_occurrence = green
 * drug_exposure = purple
 * person = blue

---
Moved from outcomesinsights/jigsaw#408
/cc @jenniferduryea

**Comment by jenniferduryea** [comment] 2017-07-27 20:24
I can see the following:

| operator | appropriate domain | operator color |
| --------------- | ------------------------------- | -------------- | 
| CPT, HCPCS | Procedure | Green |
| DRG, Revenue Code | Procedure Cost | Green | 
| Gemscript | Drug | Purple | 
| CPT or HCPCS | Procedure | Green |
| ICD-10 CM, ICD-10 Conditions, ICD-9 CM | Conditions | Red | 
| ICD-10 PCS, ICD-9 Proc | Procedure | Green |
| Drug Text String | Drug | Purple | 
| LOINC | Observation | Grey | 
| NDC, RxNorm | Drug | Purple | 
| READ | Observation | Grey | 
| Observation by Enttype | Observation | Grey | 
| WHO ATC | Drug | Purple | 
| SNOMED | Conditions | Red | 
| Condition Type | Conditions | Red | 
| Place of Service | Visit | Yellow | 
| Gender, Race | Person | Blue | 
| **Drug Type Concept** | **Drug** | **Grey** | 
| Observation Period, Information Period | Observation Period | Teal | 
| Death | Death | Brown | 
| Procedure Occurrence | Procedure | Green | 
| Visit Occurrence | Visit | Yellow | 
| **Person** | **Person** | **Grey** | 

The entries in **bold** do not seem to have a color assigned to them.  Is this intended or needs to be fixed?

**Comment by aguynamedryan** [comment] 2017-07-27 21:55
Person and DrugTypeConcept should have colors now.

**Comment by jenniferduryea** [comment] 2017-07-27 22:00
Confirmed the Person operator is blue and the drug type concept operator is purple. Closing out.

**Closed by jenniferduryea** 2017-07-27 22:00 UTC
Labels: ready to test
