### ISSUE TITLE
Add value_as_number filter to limit records by certain values

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#232] opened 2019-05-30 19:01 UTC
Add a "value_as_number filter" (I'm open to other suggestions for the operator's name) where the filter will limit the records with values passed through.  The operator should have a min and max number field where number values have to be between the two values listed.

This is for CPRD analysis, where lab values are going to be used to limit cohorts under or over certain lab thresholds (i.e. high cholesterol readings).

---
Moved from outcomesinsights/jigsaw#365
/cc @jenniferduryea @markdanese

**Comment by jenniferduryea** [comment] 2019-07-23 19:24
THis ticket has renewed interest since it directly affects a CPRD study we are using.  This is specific to the GFR values under 60 to be used as inclusion criteria for a patients.  Moving to this to Chisel 2 and tagging @aguynamedryan for implementation.

**Comment by jenniferduryea** [comment] 2019-07-23 19:24
also removing "help wanted" and "question" labels, since there are no existing questions on ticket and I don't think @aguynamedryan is getting any help on this.

**Comment by jenniferduryea** [comment] 2019-07-23 19:25
also adding that Amgen requested this as an enhancement years ago https://github.com/outcomesinsights/amgen_jigsaw_external/issues/150

**Comment by aguynamedryan** [comment] 2019-07-29 21:05
Couple more questions:

1. What kinds of numbers need to be supported?  Integers?  Decimals?
2. Is it sufficient to have just two options: "Greater Than or Equal To" and "Less Than or Equal To"?

**Comment by jenniferduryea** [comment] 2019-07-29 21:09
1. per GDM specs, measurement_details.result_as_number is set to "float".  That field is what will be used to evaluate numeric lab results.
2. I think using a range would be more flexible, similar to the age range format we have in the Protocol Builder.  But, if it's easier to have the two options specified, then I'm cool with that too.

**Comment by markdanese** [comment] 2019-07-29 21:15
decimals
We could work around anything that can be implemented.  It would be nice to have the ability to to do <, >, >=, <=, and to do 2-sided (i.e., > 5 and < 10).  

I am pretty sure we could get by without = for a long, long time.  It only works when there are just a few levels in actual use which works against the point of most continuous measures.

**Comment by aguynamedryan** [comment] 2019-08-12 17:24
I've created the NumericFilter operator.  Hopefully, it is clear how to use it?

![image](https://user-images.githubusercontent.com/117722/62884402-4ad01c80-bceb-11e9-974c-2566ca4ce34f.png)

**Comment by markdanese** [comment] 2019-08-12 18:52
If we just want one number (say <= 100), can we leave the other blank?

**Comment by jenniferduryea** [comment] 2019-08-14 17:24
I ran an export that should have resulted in some patients being included in cohort.  The export turned out to be 0 (confirmed when looking at index_001_prep temp table).  Export id 7a0124df-3a0a-4cf4-b24e-ab8183ec77d8 on chisel.jsaw.io.  Tagging @aguynamedryan for help.  Sending back to programming.

**Comment by aguynamedryan** [comment] 2019-08-15 18:27
@jenniferduryea, looks like you didn't set either of the GTE or LTE options.  I hadn't thought of this use case, and the operator simply puts a NULL in the where clause, throwing out all patients.

I assume you wanted the operator to instead act like "patient has _some_ value_as_number, I just don't care what it is"?

**Comment by jenniferduryea** [comment] 2019-08-15 18:44
Looks like the diagram editor does not save the values added to the operator.  PLease see gif below.  Is this a new ticket?  

![lab_value](https://user-images.githubusercontent.com/7853238/63118118-1316de00-bf52-11e9-9f6d-974e4a0b353b.gif)

**Comment by jenniferduryea** [comment] 2019-08-15 18:46
For the change you proposed, I think it's fine. So if you don't add any values, the result will be records where value_as_number is not NULL.

**Comment by markdanese** [comment] 2019-08-15 20:35
seems ok to me

**Comment by aguynamedryan** [comment] 2019-08-22 18:25
Values should be saving in chisel.jsaw.io now.

**Comment by jenniferduryea** [comment] 2019-08-23 22:53
tested using less than 30 and got patients with lab values at 20 and 30. Then tested using 30 in lte and gte fields and got the one patient with a lab value of 30.  Works as expected and values are saved in diagram editor.  Looks great!

**Closed by jenniferduryea** 2019-08-23 22:53 UTC
Labels: need test, ready to test

**Comment by markdanese** [comment] 2019-08-23 23:02
you mean <= 30 and got values at 20 and 30, right?

**Comment by markdanese** [comment] 2019-08-23 23:02
(I think only <= is possible)
