### ISSUE TITLE
Provider operator should return specialty type in events file

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#104] opened 2017-04-05 21:40 UTC
Currently the Provider operator only adds the Provider id to the events table but should probably add specialty type.

---
Moved from outcomesinsights/jigsaw#249
/cc @marc-outins

**Comment by jenniferduryea** [comment] 2020-07-30 22:53
I am assigning this to Chisel 04 with a higher priority. We need this for the PTCL project.  From previous discussions, it looks like @aguynamedryan would prefer to use "new columns" (or the Chisel 04 milestone) update before adding this feature.  

Tagging @markdanese for discussion if needed.  For the PTCL use case, we need to be looking at context_providers and pulling the associated specialty_type_concept_id for each context provider found.   We need to pull the specialty_concept_id.

**Comment by aguynamedryan** [comment] 2020-07-30 23:51
Old columns also uses specialty_type_concept_id.  However, I thought the issue was that we needed an operator that would just show the specialty_type_concept_id for all events, without filtering those events.

**Comment by jenniferduryea** [comment] 2020-07-31 00:45
that is the original use case.  we can use the current provider operator by filter a cpt_hcpcs operator using * and feed it into the provider filter to get all specialties seen.  that will fulfill the use case.

**Comment by jenniferduryea** [comment] 2020-08-03 22:55
Confirmed that using an * in the specialty field for the Provider Filter works to include the specialty column in the events table.  Note that it includes events with and without a specialty in output.  So if we are going to put a * in the cpt_hcpcs operator, and then a * in the provider_filter operator, we will output all of the cpt and hcpcs codes for that patient - regardless of whether that cpt/hcpcs code has a context_provider with a specialty assigned.  This makes sense, from a logical point of view.

For our use case, we may want to look into limiting the number of events fed into the provider_filter.  Of we can list all specialty_concept_ids in the specialty box to get all events with a specialty, if needed.  Closing as tested.

**Closed by jenniferduryea** 2020-08-03 22:55 UTC
Labels: enhancement, help wanted, ready to test
