### ISSUE TITLE
New asterisk for selection operators

### ISSUE THREAD

**Issue by markdanese** [outcomesinsights/conceptql#142] opened 2017-07-28 23:20 UTC
Need to check WHO ATC and do some other due diligence (per Ryan)

Users can now add an "*" in the text field for selection operators and Jigsaw will find all source_values with that vocabulary id. So, if users want to find all ICD-9 codes, they can use a * in the source_value field when adding an icd9 operator.

There are some potential issues with this - most likely stemming from bringing in a huge amount of data into the query.  We may need to see how this is working on Amgen's PROD before we make any changes and program ways around potential issues.

This is needed-by outcomesinsights/jigsaw#379 .

**Comment by jenniferduryea** [comment] 2017-07-31 18:39
Tested using asterisk in the ICD-9 operator and using "inpatient" in the provenance operator to filter out inpatient icd9 codes.  I ran this against synpuf_250 and it took 18 minutes on our side.  This seems unusually time-consuming.  But it works as intended.  We need to tell Amgen to be very careful about using this feature.

**Comment by jenniferduryea** [comment] 2017-07-31 19:47
Per #143, we need to make sure that the asterisk is not prompting sentinel study types to pull down all j codes.

**Comment by jenniferduryea** [comment] 2017-07-31 20:36
confirmed that using asterisks from in the HCPCS operator will not prompt the study builder to put days supply codes in for all of the j codes.

**Comment by jenniferduryea** [comment] 2017-08-01 23:05
confirmed that the * will also find all drug records with drug_source_vocabulary_id = 26400.  Works as intended.  Closing out.

**Closed** 2017-08-01 23:05 UTC
Labels: enhancement

**Comment by jenniferduryea** [comment] 2018-02-02 18:53
For documentation, Amgen actually requested this feature here https://github.com/outcomesinsights/amgen_jigsaw_external/issues/33.
